# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-13 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('space_post_app', '0002_article_site_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='approved_comment',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.CharField(default='名無し', max_length=200),
        ),
    ]
